### ISSUE TITLE
About training object detector on self-made datasets

### ISSUE THREAD

**Issue by YaoDongAn** [fredzzhang/hicodet#5]
Hi fredzzhang!

Thank you for your great work.I noticed that your spatio-attentive-graphs network have a good performance on HICO-DET.  

I made a dataset in HICO format, but the object type in my dataset is quite different from HICO. So, how can I modify the project to adapt to my dataset and  train my object detector? 

Thank you for your notice!

**Comment by fredzzhang** [comment]
Hi,

I'm not quite sure what you mean by "HICO format". Can you elaborate? Is it only the object class indices that are different?

**Comment by YaoDongAn** [comment]
I made a dataset which have same file format as HICO-DET. But the object categories (such as gears, bases, etc) are not included in  the  coco dataset. So, how can I modify your project  and train my object detector?

**Comment by fredzzhang** [comment]
I presume the HICO-DET file format you are referring to is the `.mat` files. Unfortunately, I re-formatted the annotations into `.json` files and no longer use the `.mat` annotations.

But that shouldn't be a problem for fine-tuning object detectors. All you need to do is to write your own dataset and replace the one I wrote (named `HICODetObject`). You can do it as below.

```python
class HICODetObject(Dataset):
    def __init__(self, ...):
        # Load and initialise your own dataset
    def __len__(self):
        # Return the number of images
    def __getitem__(self, idx):
        # Load images and bounding boxes and transform them into the following format
        # image: Tensor(C, H, W)
        # boxes: Tensor(N, 4)
        # labels: Tensor(N)
        return [image], [dict(boxes=boxes, labels=labels)]
```

Then make sure to update the instantiation part of the dataset. You should be good to go! But as a side note, a new commit I made yesterday resulted in an error #6. You should start with head 014fbbfe79413f27562d08a67b576f7905f5602b instead of the current head.

Cheers,
Fred

**Comment by YaoDongAn** [comment]
Thanks for your guidance, I'll make a try!

**Comment by YaoDongAn** [comment]
btw，can you offer the tools to transform .mat file to json？

**Comment by fredzzhang** [comment]
Sorry I don't think I kept those scripts. You don't need to convert the `.mat` files into `.json` though. You can read them in Python using `scipy.io.loadmat`. So, you can write your own dataset and load the annotations from `.mat` directly in Python.

**Comment by YaoDongAn** [comment]
Thank you for your reply. Hope you make progress on your project！
